# Generated by Django 5.0.2 on 2024-02-29 11:38

import demo_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('image', models.URLField()),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('about', models.TextField()),
                ('concepts', models.CharField(max_length=200)),
                ('github', models.URLField()),
                ('image', models.URLField()),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(default='About section not yet provided')),
                ('password', models.CharField(max_length=100)),
                ('articles', models.ManyToManyField(blank=True, to='demo_api.article')),
                ('projects', models.ManyToManyField(blank=True, to='demo_api.project')),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ['username'],
            },
            managers=[
                ('objects', demo_api.models.CustomUserManager()),
            ],
        ),
    ]
